apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      serviceAccountName: backend-ksa

      containers:
      - name: backend

        image: asia-northeast3-docker.pkg.dev/knudc-khang-buiphuoc/graphrag-repo/backend:v1

        ports:
        - containerPort: 8080

        envFrom:
        - secretRef:
            name: backend-secret

        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "knudc-khang-buiphuoc"

        - name: GOOGLE_CLOUD_LOCATION
          value: "us-central1"

        - name: NEO4J_URI
          value: "neo4j+s://8c5f9453.databases.neo4j.io"

        - name: CHROMA_CLOUD_HOST
          value: "europe-west1.gcp.trychroma.com"